export default function build(h) {
  const { buildCanvas, makeText, makeShape, makeTrack, makeAnim } = h;

  const elements = [
    makeShape("el_bg_circ", "circle", "#00A862", {
      x: 90,
      y: 510,
      w: 900,
      h: 900,
      start: 0,
      end: 15000,
      opacity: 0.12,
      name: "BG Decorative Circle",
    }),
    makeText("el_top_brand", "T H E  C O F F E E  H O U S E", {
      x: 140,
      y: 120,
      w: 800,
      h: 55,
      start: 0,
      end: 15000,
      name: "Top Brand Label",
      font: "Lato",
      size: 22,
      color: "#CBA258",
      align: "center",
    }),
    makeText("el_bottom_social", "@thecoffeehouse", {
      x: 140,
      y: 1820,
      w: 800,
      h: 50,
      start: 200,
      end: 15000,
      name: "Bottom Social",
      font: "Lato",
      size: 24,
      color: "#F2F0EB",
      align: "center",
    }),
    makeText("el_s1_welcome", "W E L C O M E  T O", {
      x: 140,
      y: 690,
      w: 800,
      h: 55,
      start: 300,
      end: 5800,
      name: "S1 Welcome",
      font: "Lato",
      size: 24,
      color: "#CBA258",
      align: "center",
    }),
    makeText("el_s1_coffee", "THE COFFEE", {
      x: 60,
      y: 760,
      w: 960,
      h: 160,
      start: 500,
      end: 5800,
      name: "S1 Coffee",
      font: "Playfair Display",
      size: 96,
      weight: 700,
      color: "#FFFFFF",
      align: "center",
    }),
    makeText("el_s1_house", "H O U S E", {
      x: 60,
      y: 930,
      w: 960,
      h: 120,
      start: 700,
      end: 5800,
      name: "S1 House",
      font: "Playfair Display",
      size: 72,
      color: "#FFFFFF",
      align: "center",
    }),
    makeShape("el_s1_line", "rect", "#CBA258", {
      x: 390,
      y: 1065,
      w: 300,
      h: 3,
      start: 1000,
      end: 5800,
      name: "S1 Divider",
    }),
    makeText("el_s1_tagline", "Crafted with Passion", {
      x: 100,
      y: 1090,
      w: 880,
      h: 70,
      start: 1200,
      end: 5800,
      name: "S1 Tagline",
      font: "Playfair Display",
      size: 34,
      color: "#F2F0EB",
      align: "center",
    }),
    makeText("el_s2_label", "O U R  S T O R Y", {
      x: 140,
      y: 690,
      w: 800,
      h: 55,
      start: 5500,
      end: 10300,
      name: "S2 Label",
      font: "Lato",
      size: 24,
      color: "#CBA258",
      align: "center",
    }),
    makeText("el_s2_every", "EVERY SIP", {
      x: 60,
      y: 760,
      w: 960,
      h: 160,
      start: 5700,
      end: 10300,
      name: "S2 Every Sip",
      font: "Playfair Display",
      size: 104,
      weight: 700,
      color: "#FFFFFF",
      align: "center",
    }),
    makeText("el_s2_tells", "TELLS A STORY", {
      x: 60,
      y: 930,
      w: 960,
      h: 100,
      start: 5900,
      end: 10300,
      name: "S2 Tells A Story",
      font: "Playfair Display",
      size: 62,
      color: "#FFFFFF",
      align: "center",
    }),
    makeShape("el_s2_line", "rect", "#CBA258", {
      x: 390,
      y: 1045,
      w: 300,
      h: 3,
      start: 6300,
      end: 10300,
      name: "S2 Divider",
    }),
    makeText("el_s2_feat1", "Premium Arabica Beans", {
      x: 100,
      y: 1070,
      w: 880,
      h: 55,
      start: 6500,
      end: 10300,
      name: "S2 Feature 1",
      font: "Lato",
      size: 30,
      color: "#F2F0EB",
      align: "center",
    }),
    makeText("el_s2_feat2", "Roasted to Perfection", {
      x: 100,
      y: 1135,
      w: 880,
      h: 55,
      start: 6800,
      end: 10300,
      name: "S2 Feature 2",
      font: "Lato",
      size: 30,
      color: "#F2F0EB",
      align: "center",
    }),
    makeText("el_s2_feat3", "Served with Care", {
      x: 100,
      y: 1200,
      w: 880,
      h: 55,
      start: 7100,
      end: 10300,
      name: "S2 Feature 3",
      font: "Lato",
      size: 30,
      color: "#F2F0EB",
      align: "center",
    }),
    makeShape("el_s3_acc_circ", "circle", "#00A862", {
      x: 190,
      y: 510,
      w: 700,
      h: 700,
      start: 10000,
      end: 15000,
      opacity: 0.18,
      name: "S3 Accent Circle",
    }),
    makeText("el_s3_label", "F I N D  U S", {
      x: 140,
      y: 680,
      w: 800,
      h: 55,
      start: 10200,
      end: 15000,
      name: "S3 Label",
      font: "Lato",
      size: 24,
      color: "#CBA258",
      align: "center",
    }),
    makeText("el_s3_visit", "VISIT US", {
      x: 60,
      y: 750,
      w: 960,
      h: 180,
      start: 10400,
      end: 15000,
      name: "S3 Visit",
      font: "Playfair Display",
      size: 116,
      weight: 700,
      color: "#FFFFFF",
      align: "center",
    }),
    makeText("el_s3_today", "TODAY", {
      x: 60,
      y: 940,
      w: 960,
      h: 130,
      start: 10600,
      end: 15000,
      name: "S3 Today",
      font: "Playfair Display",
      size: 80,
      color: "#FFFFFF",
      align: "center",
    }),
    makeShape("el_s3_line", "rect", "#CBA258", {
      x: 390,
      y: 1085,
      w: 300,
      h: 3,
      start: 11000,
      end: 15000,
      name: "S3 Divider",
    }),
    makeText("el_s3_address", "123 Coffee Lane, Downtown", {
      x: 100,
      y: 1110,
      w: 880,
      h: 65,
      start: 11200,
      end: 15000,
      name: "S3 Address",
      font: "Lato",
      size: 30,
      color: "#F2F0EB",
      align: "center",
    }),
    makeText("el_s3_hours", "Open Daily  7AM - 10PM", {
      x: 100,
      y: 1185,
      w: 880,
      h: 55,
      start: 11400,
      end: 15000,
      name: "S3 Hours",
      font: "Lato",
      size: 28,
      color: "#CBA258",
      align: "center",
    }),
    makeShape("el_s3_btn", "rect", "#00A862", {
      x: 290,
      y: 1265,
      w: 500,
      h: 90,
      start: 11800,
      end: 15000,
      name: "S3 Button BG",
      rx: 45,
      ry: 45,
    }),
    makeText("el_s3_btn_txt", "ORDER NOW", {
      x: 290,
      y: 1282,
      w: 500,
      h: 56,
      start: 12000,
      end: 15000,
      name: "S3 Button Text",
      font: "Lato",
      size: 28,
      weight: 700,
      color: "#FFFFFF",
      align: "center",
    }),
  ];

  const tracks = [
    makeTrack("track_bg", "Background", "shape", ["el_bg_circ"]),
    makeTrack("track_persistent", "Persistent Labels", "text", ["el_top_brand","el_bottom_social"]),
    makeTrack("track_s1_text", "Scene 1 Text", "text", ["el_s1_welcome","el_s1_coffee","el_s1_house","el_s1_tagline"]),
    makeTrack("track_s1_shapes", "Scene 1 Shapes", "shape", ["el_s1_line"]),
    makeTrack("track_s2_text", "Scene 2 Text", "text", ["el_s2_label","el_s2_every","el_s2_tells","el_s2_feat1","el_s2_feat2","el_s2_feat3"]),
    makeTrack("track_s2_shapes", "Scene 2 Shapes", "shape", ["el_s2_line"]),
    makeTrack("track_s3_text", "Scene 3 Text", "text", ["el_s3_label","el_s3_visit","el_s3_today","el_s3_address","el_s3_hours","el_s3_btn_txt"]),
    makeTrack("track_s3_shapes", "Scene 3 Shapes", "shape", ["el_s3_acc_circ","el_s3_line","el_s3_btn"]),
  ];

  const animations = [
    makeAnim("anim_bg_breathe", "el_bg_circ", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_top_in", "el_top_brand", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("anim_bottom_in", "el_bottom_social", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_welcome_in", "el_s1_welcome", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_coffee_in", "el_s1_coffee", "slideIn", 900, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_house_in", "el_s1_house", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_line_in", "el_s1_line", "fadeIn", 400, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_tagline_in", "el_s1_tagline", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_s1_welcome_out", "el_s1_welcome", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s1_coffee_out", "el_s1_coffee", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("anim_s1_house_out", "el_s1_house", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("anim_s1_line_out", "el_s1_line", "fadeOut", 300, "out", {"easing":"easeIn"}),
    makeAnim("anim_s1_tagline_out", "el_s1_tagline", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_label_in", "el_s2_label", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_every_in", "el_s2_every", "slideIn", 900, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_tells_in", "el_s2_tells", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_line_in", "el_s2_line", "fadeIn", 400, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_feat1_in", "el_s2_feat1", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_feat2_in", "el_s2_feat2", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_feat3_in", "el_s2_feat3", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s2_label_out", "el_s2_label", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_every_out", "el_s2_every", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_tells_out", "el_s2_tells", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_line_out", "el_s2_line", "fadeOut", 300, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_feat1_out", "el_s2_feat1", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_feat2_out", "el_s2_feat2", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s2_feat3_out", "el_s2_feat3", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_s3_acc_in", "el_s3_acc_circ", "zoomIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_acc_pulse", "el_s3_acc_circ", "pulse", 2000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_s3_label_in", "el_s3_label", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_visit_in", "el_s3_visit", "slideIn", 900, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_today_in", "el_s3_today", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_line_in", "el_s3_line", "fadeIn", 400, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_address_in", "el_s3_address", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_hours_in", "el_s3_hours", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_btn_in", "el_s3_btn", "zoomIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("anim_s3_btn_txt_in", "el_s3_btn_txt", "fadeIn", 400, "in", {"easing":"easeOut"}),
  ];

  return buildCanvas({
    width: 1080,
    height: 1920,
    bg: "#1E3932",
    maxTime: 15000,
    fontAssets: {"Playfair Display":{"url":"data/fonts/PlayfairDisplay-Variable.ttf","fileType":"ttf"},"Lato":{"url":"data/fonts/Lato-Regular.ttf","fileType":"ttf"}},
    elements,
    tracks,
    animations,
    quality: "high",
  });
}
