export default function build(h) {
  const { buildCanvas, makeText, makeTrack, makeAnim } = h;

  const elements = [
    makeText("el_s1_pre", "Introducing", {
      x: 560,
      y: 380,
      w: 800,
      h: 30,
      start: 500,
      end: 5000,
      opacity: 0.5,
      name: "Pre Title",
      size: 28,
      weight: 300,
      color: "#a0a0a0",
      align: "center",
    }),
    makeText("el_s1_name", "AirPods Ultra", {
      x: 210,
      y: 430,
      w: 1500,
      h: 130,
      start: 1000,
      end: 5000,
      name: "Product Name",
      size: 108,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s1_tag", "Sound beyond imagination.", {
      x: 410,
      y: 590,
      w: 1100,
      h: 50,
      start: 2000,
      end: 5000,
      name: "Tagline",
      size: 40,
      weight: 300,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s2_label", "KEY FEATURES", {
      x: 560,
      y: 180,
      w: 800,
      h: 25,
      start: 5000,
      end: 12000,
      opacity: 0.4,
      name: "Features Label",
      size: 18,
      weight: 600,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s2_f1_val", "50 dB", {
      x: 160,
      y: 300,
      w: 500,
      h: 80,
      start: 5500,
      end: 12000,
      name: "Feature 1 Value",
      size: 72,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s2_f1_desc", "Active Noise Cancellation", {
      x: 160,
      y: 400,
      w: 500,
      h: 35,
      start: 5800,
      end: 12000,
      name: "Feature 1 Desc",
      size: 24,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s2_f2_val", "48 hrs", {
      x: 710,
      y: 300,
      w: 500,
      h: 80,
      start: 6500,
      end: 12000,
      name: "Feature 2 Value",
      size: 72,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s2_f2_desc", "Battery Life with Case", {
      x: 710,
      y: 400,
      w: 500,
      h: 35,
      start: 6800,
      end: 12000,
      name: "Feature 2 Desc",
      size: 24,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s2_f3_val", "IP68", {
      x: 1260,
      y: 300,
      w: 500,
      h: 80,
      start: 7500,
      end: 12000,
      name: "Feature 3 Value",
      size: 72,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s2_f3_desc", "Water & Dust Resistant", {
      x: 1260,
      y: 400,
      w: 500,
      h: 35,
      start: 7800,
      end: 12000,
      name: "Feature 3 Desc",
      size: 24,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s2_highlight", "Spatial Audio with head tracking", {
      x: 310,
      y: 560,
      w: 1300,
      h: 80,
      start: 9000,
      end: 12000,
      name: "Highlight",
      size: 48,
      weight: 600,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s2_highlight_sub", "Immersive 3D sound that surrounds you", {
      x: 410,
      y: 660,
      w: 1100,
      h: 40,
      start: 9500,
      end: 12000,
      name: "Highlight Sub",
      size: 28,
      weight: 300,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s3_price_label", "Starting at", {
      x: 660,
      y: 360,
      w: 600,
      h: 30,
      start: 12000,
      end: 19000,
      opacity: 0.5,
      name: "Price Label",
      size: 24,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s3_price", "$249", {
      x: 460,
      y: 410,
      w: 1000,
      h: 120,
      start: 12500,
      end: 19000,
      name: "Price",
      size: 108,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s3_colors", "Midnight  ·  Starlight  ·  Storm Blue", {
      x: 510,
      y: 570,
      w: 900,
      h: 40,
      start: 13500,
      end: 19000,
      name: "Colors",
      size: 28,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s3_avail", "Available March 28", {
      x: 560,
      y: 660,
      w: 800,
      h: 35,
      start: 14500,
      end: 19000,
      name: "Availability",
      size: 28,
      weight: 600,
      color: "#2997ff",
      align: "center",
    }),
    makeText("el_s4_name", "AirPods Ultra", {
      x: 310,
      y: 380,
      w: 1300,
      h: 100,
      start: 19000,
      end: 25000,
      name: "Closing Name",
      size: 72,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s4_tag", "Sound beyond imagination.", {
      x: 510,
      y: 500,
      w: 900,
      h: 40,
      start: 19800,
      end: 25000,
      name: "Closing Tag",
      size: 32,
      weight: 300,
      color: "#86868b",
      align: "center",
    }),
    makeText("el_s4_cta", "Pre-order now at apple.com", {
      x: 660,
      y: 590,
      w: 600,
      h: 35,
      start: 20800,
      end: 25000,
      name: "CTA",
      size: 24,
      color: "#2997ff",
      align: "center",
    }),
  ];

  const tracks = [
    makeTrack("track_text", "Text", "text", ["el_s1_pre","el_s1_name","el_s1_tag","el_s2_label","el_s2_f1_val","el_s2_f1_desc","el_s2_f2_val","el_s2_f2_desc","el_s2_f3_val","el_s2_f3_desc","el_s2_highlight","el_s2_highlight_sub","el_s3_price_label","el_s3_price","el_s3_colors","el_s3_avail","el_s4_name","el_s4_tag","el_s4_cta"]),
  ];

  const animations = [
    makeAnim("a_01", "el_s1_pre", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_02", "el_s1_pre", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_03", "el_s1_name", "fadeIn", 1200, "in", {"easing":"easeOut"}),
    makeAnim("a_04", "el_s1_name", "fadeOut", 700, "out", {"easing":"easeIn"}),
    makeAnim("a_05", "el_s1_tag", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_06", "el_s1_tag", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_10", "el_s2_label", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_11", "el_s2_label", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_12", "el_s2_f1_val", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_13", "el_s2_f1_val", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_14", "el_s2_f1_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_15", "el_s2_f1_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_16", "el_s2_f2_val", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_17", "el_s2_f2_val", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_18", "el_s2_f2_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_19", "el_s2_f2_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_20", "el_s2_f3_val", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_21", "el_s2_f3_val", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_22", "el_s2_f3_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_23", "el_s2_f3_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_24", "el_s2_highlight", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_25", "el_s2_highlight", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_26", "el_s2_highlight_sub", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_27", "el_s2_highlight_sub", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_30", "el_s3_price_label", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_31", "el_s3_price_label", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_32", "el_s3_price", "fadeIn", 1200, "in", {"easing":"easeOut"}),
    makeAnim("a_33", "el_s3_price", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_34", "el_s3_colors", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_35", "el_s3_colors", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_36", "el_s3_avail", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_37", "el_s3_avail", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_40", "el_s4_name", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_41", "el_s4_tag", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_42", "el_s4_cta", "fadeIn", 800, "in", {"easing":"easeOut"}),
  ];

  return buildCanvas({
    bg: "#000000",
    maxTime: 25000,
    elements,
    tracks,
    animations,
    quality: "high",
  });
}
