export default function build(h) {
  const { buildCanvas, makeText, makeShape, makeAudio, makeTrack, makeAnim, makeKfTrack, makeKf, makeTransition, makeCaption } = h;

  const elements = [
    makeShape("el_deco_circle1", "circle", "#4F6AFF", {
      x: 1400,
      y: -200,
      w: 700,
      h: 700,
      start: 0,
      end: 42000,
      opacity: 0.06,
      name: "Deco Circle Top-Right",
    }),
    makeShape("el_deco_circle2", "circle", "#7C5CFC", {
      x: -200,
      y: 600,
      w: 600,
      h: 600,
      start: 0,
      end: 42000,
      opacity: 0.05,
      name: "Deco Circle Bottom-Left",
    }),
    makeShape("el_top_bar", "rect", "#4F6AFF", {
      x: 0,
      y: 0,
      w: 1920,
      h: 5,
      start: 0,
      end: 42000,
      name: "Top Accent Bar",
    }),
    makeText("el_hero_name", "hypr-video-cli", {
      x: 260,
      y: 280,
      w: 1400,
      h: 160,
      start: 0,
      end: 5500,
      name: "Hero Product Name",
      font: "Montserrat",
      size: 96,
      weight: 700,
      color: "#0f1629",
      align: "center",
      charSpacing: 2,
      shadowColor: "rgba(79,106,255,0.15)",
      shadowBlur: 20,
    }),
    makeText("el_hero_tag", "Programmatic Video Generation from Your Terminal", {
      x: 360,
      y: 460,
      w: 1200,
      h: 50,
      start: 1000,
      end: 5500,
      name: "Hero Tagline",
      font: "Montserrat",
      size: 28,
      color: "#4F6AFF",
      align: "center",
      charSpacing: 2,
    }),
    makeText("el_hero_desc", "Describe your video in natural language. Get polished MP4 in seconds.", {
      x: 410,
      y: 530,
      w: 1100,
      h: 50,
      start: 1800,
      end: 5500,
      name: "Hero Description",
      font: "Montserrat",
      size: 22,
      color: "#2d3550",
      align: "center",
    }),
    makeText("el_hero_badge", "Open Source  •  MIT License  •  Node.js >= 20", {
      x: 710,
      y: 610,
      w: 500,
      h: 36,
      start: 2400,
      end: 5500,
      opacity: 0.9,
      name: "Hero Badge",
      font: "Montserrat",
      size: 21,
      color: "#4a5670",
      align: "center",
    }),
    makeShape("el_line1", "rect", "#4F6AFF", {
      x: 810,
      y: 445,
      w: 300,
      h: 3,
      start: 600,
      end: 5500,
      opacity: 0.5,
      name: "Hero Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeText("el_pipe_title", "How It Works", {
      x: 360,
      y: 180,
      w: 1200,
      h: 80,
      start: 6000,
      end: 12000,
      name: "Pipeline Title",
      font: "Montserrat",
      size: 56,
      weight: 700,
      color: "#0f1629",
      align: "center",
      shadowColor: "rgba(79,106,255,0.12)",
      shadowBlur: 16,
    }),
    makeText("el_pipe_sub", "Three simple steps to create professional videos", {
      x: 460,
      y: 270,
      w: 1000,
      h: 40,
      start: 6000,
      end: 12000,
      opacity: 0.9,
      name: "Pipeline Subtitle",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
    }),
    makeShape("el_line2", "rect", "#4F6AFF", {
      x: 860,
      y: 310,
      w: 200,
      h: 3,
      start: 6000,
      end: 12000,
      opacity: 0.4,
      name: "Pipeline Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeShape("el_card1_bg", "rect", "#ffffff", {
      x: 120,
      y: 350,
      w: 520,
      h: 260,
      start: 6800,
      end: 12000,
      name: "Card 1 BG",
      rx: 16,
      ry: 16,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_step1_num", "01", {
      x: 140,
      y: 350,
      w: 100,
      h: 80,
      start: 6800,
      end: 12000,
      opacity: 0.15,
      name: "Step 1 Number",
      font: "Montserrat",
      size: 64,
      weight: 700,
      color: "#4F6AFF",
    }),
    makeText("el_step1", "Describe Your Video", {
      x: 150,
      y: 420,
      w: 470,
      h: 40,
      start: 6800,
      end: 12000,
      name: "Step 1 Title",
      font: "Montserrat",
      size: 26,
      weight: 700,
      color: "#0f1629",
      align: "center",
    }),
    makeText("el_step1_desc", "Tell Claude what you want\nin plain English", {
      x: 150,
      y: 470,
      w: 470,
      h: 80,
      start: 7200,
      end: 12000,
      opacity: 0.9,
      name: "Step 1 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
      lineHeight: 1.5,
    }),
    makeShape("el_card2_bg", "rect", "#ffffff", {
      x: 700,
      y: 350,
      w: 520,
      h: 260,
      start: 7600,
      end: 12000,
      name: "Card 2 BG",
      rx: 16,
      ry: 16,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_step2_num", "02", {
      x: 720,
      y: 350,
      w: 100,
      h: 80,
      start: 7600,
      end: 12000,
      opacity: 0.15,
      name: "Step 2 Number",
      font: "Montserrat",
      size: 64,
      weight: 700,
      color: "#4F6AFF",
    }),
    makeText("el_step2", "Generate JSON", {
      x: 730,
      y: 420,
      w: 470,
      h: 40,
      start: 7600,
      end: 12000,
      name: "Step 2 Title",
      font: "Montserrat",
      size: 26,
      weight: 700,
      color: "#0f1629",
      align: "center",
    }),
    makeText("el_step2_desc", "Claude builds canvasState\nwith elements & animations", {
      x: 730,
      y: 470,
      w: 470,
      h: 80,
      start: 8000,
      end: 12000,
      opacity: 0.9,
      name: "Step 2 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
      lineHeight: 1.5,
    }),
    makeShape("el_card3_bg", "rect", "#ffffff", {
      x: 1280,
      y: 350,
      w: 520,
      h: 260,
      start: 8400,
      end: 12000,
      name: "Card 3 BG",
      rx: 16,
      ry: 16,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_step3_num", "03", {
      x: 1300,
      y: 350,
      w: 100,
      h: 80,
      start: 8400,
      end: 12000,
      opacity: 0.15,
      name: "Step 3 Number",
      font: "Montserrat",
      size: 64,
      weight: 700,
      color: "#4F6AFF",
    }),
    makeText("el_step3", "Render MP4", {
      x: 1310,
      y: 420,
      w: 470,
      h: 40,
      start: 8400,
      end: 12000,
      name: "Step 3 Title",
      font: "Montserrat",
      size: 26,
      weight: 700,
      color: "#0f1629",
      align: "center",
    }),
    makeText("el_step3_desc", "CLI renders via\nskia-canvas + FFmpeg", {
      x: 1310,
      y: 470,
      w: 470,
      h: 80,
      start: 8800,
      end: 12000,
      opacity: 0.9,
      name: "Step 3 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
      lineHeight: 1.5,
    }),
    makeText("el_pipe_cmd", "npx hypr-video-cli input.json -o output.mp4", {
      x: 460,
      y: 650,
      w: 1000,
      h: 40,
      start: 9800,
      end: 12000,
      opacity: 0.8,
      name: "Pipeline Command",
      font: "Fira Code",
      size: 20,
      color: "#4F6AFF",
      align: "center",
    }),
    makeText("el_feat_title", "Everything You Need", {
      x: 360,
      y: 160,
      w: 1200,
      h: 80,
      start: 12500,
      end: 19000,
      name: "Features Title",
      font: "Montserrat",
      size: 56,
      weight: 700,
      color: "#0f1629",
      align: "center",
      shadowColor: "rgba(79,106,255,0.12)",
      shadowBlur: 16,
    }),
    makeText("el_feat_sub", "A complete toolkit for programmatic video creation", {
      x: 410,
      y: 250,
      w: 1100,
      h: 40,
      start: 12500,
      end: 19000,
      opacity: 0.9,
      name: "Features Subtitle",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
    }),
    makeShape("el_line3", "rect", "#4F6AFF", {
      x: 860,
      y: 290,
      w: 200,
      h: 3,
      start: 12500,
      end: 19000,
      opacity: 0.4,
      name: "Features Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeShape("el_feat_dot1", "circle", "#4F6AFF", {
      x: 305,
      y: 340,
      w: 16,
      h: 16,
      start: 13200,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 1",
    }),
    makeText("el_feat1", "30+ Animations — fade, slide, zoom, bounce, wave, character effects", {
      x: 340,
      y: 330,
      w: 1300,
      h: 40,
      start: 13200,
      end: 19000,
      name: "Feature 1",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeShape("el_feat_dot2", "circle", "#7C5CFC", {
      x: 305,
      y: 400,
      w: 16,
      h: 16,
      start: 14000,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 2",
    }),
    makeText("el_feat2", "20+ Transitions — crossfade, wipe, iris, glitch, blur between clips", {
      x: 340,
      y: 390,
      w: 1300,
      h: 40,
      start: 14000,
      end: 19000,
      name: "Feature 2",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeShape("el_feat_dot3", "circle", "#4F6AFF", {
      x: 305,
      y: 460,
      w: 16,
      h: 16,
      start: 14800,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 3",
    }),
    makeText("el_feat3", "50+ Visual Effects — glow, VHS, rain, snow, fire, neon & more", {
      x: 340,
      y: 450,
      w: 1300,
      h: 40,
      start: 14800,
      end: 19000,
      name: "Feature 3",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeShape("el_feat_dot4", "circle", "#7C5CFC", {
      x: 305,
      y: 520,
      w: 16,
      h: 16,
      start: 15600,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 4",
    }),
    makeText("el_feat4", "Keyframe Animation — position, scale, rotation, opacity over time", {
      x: 340,
      y: 510,
      w: 1300,
      h: 40,
      start: 15600,
      end: 19000,
      name: "Feature 4",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeShape("el_feat_dot5", "circle", "#4F6AFF", {
      x: 305,
      y: 580,
      w: 16,
      h: 16,
      start: 16400,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 5",
    }),
    makeText("el_feat5", "Timed Captions with word-level karaoke highlighting", {
      x: 340,
      y: 570,
      w: 1300,
      h: 40,
      start: 16400,
      end: 19000,
      name: "Feature 5",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeShape("el_feat_dot6", "circle", "#7C5CFC", {
      x: 305,
      y: 640,
      w: 16,
      h: 16,
      start: 17200,
      end: 19000,
      opacity: 0.8,
      name: "Feature Dot 6",
    }),
    makeText("el_feat6", "Text, Images, Video, Shapes, Audio — composable on a timeline", {
      x: 340,
      y: 630,
      w: 1300,
      h: 40,
      start: 17200,
      end: 19000,
      name: "Feature 6",
      font: "Montserrat",
      size: 24,
      weight: 500,
      color: "#0f1629",
    }),
    makeText("el_use_title", "Built for Every Format", {
      x: 360,
      y: 160,
      w: 1200,
      h: 80,
      start: 19500,
      end: 25500,
      name: "Use Cases Title",
      font: "Montserrat",
      size: 56,
      weight: 700,
      color: "#0f1629",
      align: "center",
      shadowColor: "rgba(79,106,255,0.12)",
      shadowBlur: 16,
    }),
    makeText("el_use_sub", "From YouTube to TikTok — any aspect ratio, any use case", {
      x: 410,
      y: 250,
      w: 1100,
      h: 40,
      start: 19500,
      end: 25500,
      opacity: 0.9,
      name: "Use Cases Subtitle",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
    }),
    makeShape("el_line_use", "rect", "#4F6AFF", {
      x: 860,
      y: 290,
      w: 200,
      h: 3,
      start: 19500,
      end: 25500,
      opacity: 0.4,
      name: "Use Cases Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeShape("el_ucard1", "rect", "#ffffff", {
      x: 120,
      y: 330,
      w: 830,
      h: 140,
      start: 20200,
      end: 25500,
      name: "Use Card 1",
      rx: 12,
      ry: 12,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_use1", "Product Launch Videos", {
      x: 150,
      y: 345,
      w: 770,
      h: 40,
      start: 20200,
      end: 25500,
      name: "Use Case 1",
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#0f1629",
    }),
    makeText("el_use1_desc", "Feature specs, pricing, CTA — ready in minutes", {
      x: 150,
      y: 395,
      w: 770,
      h: 35,
      start: 20500,
      end: 25500,
      opacity: 0.85,
      name: "Use Case 1 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
    }),
    makeShape("el_ucard2", "rect", "#ffffff", {
      x: 970,
      y: 330,
      w: 830,
      h: 140,
      start: 21000,
      end: 25500,
      name: "Use Card 2",
      rx: 12,
      ry: 12,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_use2", "Social Media Content", {
      x: 1000,
      y: 345,
      w: 770,
      h: 40,
      start: 21000,
      end: 25500,
      name: "Use Case 2",
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#0f1629",
    }),
    makeText("el_use2_desc", "9:16 Stories, 1:1 Square, 16:9 YouTube", {
      x: 1000,
      y: 395,
      w: 770,
      h: 35,
      start: 21300,
      end: 25500,
      opacity: 0.85,
      name: "Use Case 2 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
    }),
    makeShape("el_ucard3", "rect", "#ffffff", {
      x: 120,
      y: 490,
      w: 830,
      h: 140,
      start: 21800,
      end: 25500,
      name: "Use Card 3",
      rx: 12,
      ry: 12,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_use3", "Tutorial Intros", {
      x: 150,
      y: 505,
      w: 770,
      h: 40,
      start: 21800,
      end: 25500,
      name: "Use Case 3",
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#0f1629",
    }),
    makeText("el_use3_desc", "Step-by-step slides with numbered sections", {
      x: 150,
      y: 555,
      w: 770,
      h: 35,
      start: 22100,
      end: 25500,
      opacity: 0.85,
      name: "Use Case 3 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
    }),
    makeShape("el_ucard4", "rect", "#ffffff", {
      x: 970,
      y: 490,
      w: 830,
      h: 140,
      start: 22600,
      end: 25500,
      name: "Use Card 4",
      rx: 12,
      ry: 12,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_use4", "Event Announcements", {
      x: 1000,
      y: 505,
      w: 770,
      h: 40,
      start: 22600,
      end: 25500,
      name: "Use Case 4",
      font: "Montserrat",
      size: 26,
      weight: 600,
      color: "#0f1629",
    }),
    makeText("el_use4_desc", "Conference promos with speaker lineups", {
      x: 1000,
      y: 555,
      w: 770,
      h: 35,
      start: 22900,
      end: 25500,
      opacity: 0.85,
      name: "Use Case 4 Detail",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
    }),
    makeText("el_use_formats", "Output: MP4 (H.264)  •  MOV  •  MP3  •  24/30/60 fps", {
      x: 360,
      y: 670,
      w: 1200,
      h: 36,
      start: 23500,
      end: 25500,
      opacity: 0.9,
      name: "Output Formats",
      font: "Fira Code",
      size: 19,
      color: "#4a5670",
      align: "center",
    }),
    makeText("el_ai_title", "AI-Powered Workflow", {
      x: 260,
      y: 180,
      w: 1400,
      h: 80,
      start: 26000,
      end: 32500,
      name: "AI Title",
      font: "Montserrat",
      size: 56,
      weight: 700,
      color: "#0f1629",
      align: "center",
      shadowColor: "rgba(79,106,255,0.12)",
      shadowBlur: 16,
    }),
    makeText("el_ai_sub", "Ships as a Claude Code Skill — no manual JSON editing needed", {
      x: 410,
      y: 270,
      w: 1100,
      h: 40,
      start: 26000,
      end: 32500,
      opacity: 0.9,
      name: "AI Subtitle",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
    }),
    makeShape("el_line4", "rect", "#4F6AFF", {
      x: 860,
      y: 310,
      w: 200,
      h: 3,
      start: 26000,
      end: 32500,
      opacity: 0.4,
      name: "AI Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeShape("el_ai_card", "rect", "#ffffff", {
      x: 260,
      y: 350,
      w: 1400,
      h: 320,
      start: 27000,
      end: 32500,
      name: "AI Card BG",
      rx: 16,
      ry: 16,
      stroke: "#c8d1e0",
      strokeWidth: 1,
    }),
    makeText("el_ai_desc", "Just describe what you want:", {
      x: 310,
      y: 370,
      w: 1300,
      h: 40,
      start: 27000,
      end: 32500,
      name: "AI Description",
      font: "Montserrat",
      size: 24,
      weight: 600,
      color: "#0f1629",
    }),
    makeText("el_ai_cmd", "\"Create a 15s product launch with animated title and pricing CTA\"", {
      x: 310,
      y: 430,
      w: 1300,
      h: 40,
      start: 28000,
      end: 32500,
      opacity: 0.85,
      name: "AI Command Example",
      font: "Fira Code",
      size: 19,
      color: "#4F6AFF",
    }),
    makeText("el_ai_flow", "Claude reads skill/references/ → builds JSON → validates → renders MP4", {
      x: 310,
      y: 500,
      w: 1300,
      h: 40,
      start: 29000,
      end: 32500,
      opacity: 0.9,
      name: "AI Flow",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
    }),
    makeText("el_ai_install", "Install:  /install-skill ./hypr-video-cli/skill", {
      x: 310,
      y: 570,
      w: 1300,
      h: 36,
      start: 30000,
      end: 32500,
      opacity: 0.85,
      name: "AI Install",
      font: "Fira Code",
      size: 20,
      color: "#7C5CFC",
    }),
    makeText("el_cta_title", "Start Building Today", {
      x: 360,
      y: 200,
      w: 1200,
      h: 100,
      start: 33500,
      end: 42000,
      name: "CTA Title",
      font: "Montserrat",
      size: 72,
      weight: 700,
      color: "#0f1629",
      align: "center",
      shadowColor: "rgba(79,106,255,0.15)",
      shadowBlur: 20,
    }),
    makeShape("el_line5", "rect", "#4F6AFF", {
      x: 810,
      y: 320,
      w: 300,
      h: 3,
      start: 33500,
      end: 42000,
      opacity: 0.4,
      name: "CTA Accent Line",
      rx: 2,
      ry: 2,
    }),
    makeShape("el_cta_card", "rect", "#4F6AFF", {
      x: 410,
      y: 360,
      w: 1100,
      h: 60,
      start: 34500,
      end: 42000,
      name: "CTA Card BG",
      rx: 12,
      ry: 12,
    }),
    makeText("el_cta_cmd", "npx hypr-video-cli input.json -o output.mp4", {
      x: 410,
      y: 370,
      w: 1100,
      h: 45,
      start: 34500,
      end: 42000,
      name: "CTA Command",
      font: "Fira Code",
      size: 24,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_cta_install", "npm install -g hypr-video-cli", {
      x: 510,
      y: 450,
      w: 900,
      h: 40,
      start: 35500,
      end: 42000,
      opacity: 0.8,
      name: "CTA Install",
      font: "Fira Code",
      size: 20,
      color: "#4F6AFF",
      align: "center",
    }),
    makeText("el_cta_info", "Open Source  •  MIT License  •  Node.js >= 20  •  FFmpeg", {
      x: 410,
      y: 520,
      w: 1100,
      h: 40,
      start: 36500,
      end: 42000,
      opacity: 0.9,
      name: "CTA Info",
      font: "Montserrat",
      size: 20,
      color: "#2d3550",
      align: "center",
    }),
    makeText("el_cta_examples", "15+ example templates included — hello-world, product-launch, sale-countdown & more", {
      x: 360,
      y: 580,
      w: 1200,
      h: 36,
      start: 37500,
      end: 42000,
      opacity: 0.85,
      name: "CTA Examples",
      font: "Montserrat",
      size: 20,
      color: "#4a5670",
      align: "center",
    }),
    makeText("el_cta_star", "★  Star us on GitHub", {
      x: 660,
      y: 650,
      w: 600,
      h: 40,
      start: 38500,
      end: 42000,
      opacity: 0.8,
      name: "CTA Star",
      font: "Montserrat",
      size: 22,
      weight: 600,
      color: "#4F6AFF",
      align: "center",
    }),
    makeAudio("el_bgm", "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3", { start: 0, end: 42000, volume: 0.2 }),
  ];

  const tracks = [
    makeTrack("track_titles", "Section Titles", "text", ["el_hero_name","el_pipe_title","el_feat_title","el_use_title","el_ai_title","el_cta_title"]),
    makeTrack("track_sub1", "Row 1", "text", ["el_hero_tag","el_pipe_sub","el_feat_sub","el_use_sub","el_ai_sub","el_cta_cmd"]),
    makeTrack("track_sub2", "Row 2", "text", ["el_hero_desc","el_step1","el_feat1","el_use1","el_ai_desc","el_cta_install"]),
    makeTrack("track_sub3", "Row 3", "text", ["el_hero_badge","el_step1_desc","el_feat2","el_use1_desc","el_ai_cmd","el_cta_info"]),
    makeTrack("track_sub4", "Row 4", "text", ["el_step2","el_feat3","el_use2","el_ai_flow","el_cta_examples"]),
    makeTrack("track_sub5", "Row 5", "text", ["el_step2_desc","el_feat4","el_use2_desc","el_ai_install","el_cta_star"]),
    makeTrack("track_sub6", "Row 6", "text", ["el_step3","el_feat5","el_use3"]),
    makeTrack("track_sub7", "Row 7", "text", ["el_step3_desc","el_feat6","el_use3_desc"]),
    makeTrack("track_sub8", "Row 8", "text", ["el_pipe_cmd","el_use4","el_use_formats"]),
    makeTrack("track_sub9", "Row 9", "text", ["el_step1_num","el_step2_num","el_step3_num","el_use4_desc"]),
    makeTrack("track_lines", "Accent Lines", "shape", ["el_top_bar","el_line1","el_line2","el_line3","el_line_use","el_line4","el_line5"]),
    makeTrack("track_dots", "Feature Dots", "shape", ["el_feat_dot1","el_feat_dot2","el_feat_dot3","el_feat_dot4","el_feat_dot5","el_feat_dot6"]),
    makeTrack("track_cards", "Cards", "shape", ["el_card1_bg","el_card2_bg","el_card3_bg","el_ucard1","el_ucard2","el_ucard3","el_ucard4","el_ai_card","el_cta_card"]),
    makeTrack("track_deco", "Decorations", "shape", ["el_deco_circle1","el_deco_circle2"]),
    makeTrack("track_audio", "Music", "audio", ["el_bgm"]),
  ];

  const animations = [
    makeAnim("a_hero_in", "el_hero_name", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_hero_out", "el_hero_name", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_htag_in", "el_hero_tag", "slideIn", 800, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_htag_out", "el_hero_tag", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_hdesc_in", "el_hero_desc", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("a_hdesc_out", "el_hero_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_hbadge_in", "el_hero_badge", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_hbadge_out", "el_hero_badge", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_pt_in", "el_pipe_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_pt_out", "el_pipe_title", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_ps_in", "el_pipe_sub", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ps_out", "el_pipe_sub", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_c1_in", "el_card1_bg", "slideIn", 700, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_c1_out", "el_card1_bg", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_s1n_in", "el_step1_num", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_s1_in", "el_step1", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_s1d_in", "el_step1_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_c2_in", "el_card2_bg", "slideIn", 700, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_c2_out", "el_card2_bg", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_s2n_in", "el_step2_num", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_s2_in", "el_step2", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_s2d_in", "el_step2_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_c3_in", "el_card3_bg", "slideIn", 700, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_c3_out", "el_card3_bg", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_s3n_in", "el_step3_num", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_s3_in", "el_step3", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_s3d_in", "el_step3_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_pcmd_in", "el_pipe_cmd", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ft_in", "el_feat_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_ft_out", "el_feat_title", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_fs_in", "el_feat_sub", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_fs_out", "el_feat_sub", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f1_in", "el_feat1", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f1_out", "el_feat1", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f2_in", "el_feat2", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f2_out", "el_feat2", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f3_in", "el_feat3", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f3_out", "el_feat3", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f4_in", "el_feat4", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f4_out", "el_feat4", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f5_in", "el_feat5", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f5_out", "el_feat5", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_f6_in", "el_feat6", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_f6_out", "el_feat6", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_fd1_in", "el_feat_dot1", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_fd2_in", "el_feat_dot2", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_fd3_in", "el_feat_dot3", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_fd4_in", "el_feat_dot4", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_fd5_in", "el_feat_dot5", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_fd6_in", "el_feat_dot6", "zoomIn", 300, "in", {"easing":"easeOut"}),
    makeAnim("a_ut_in", "el_use_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_ut_out", "el_use_title", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_us_in", "el_use_sub", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_us_out", "el_use_sub", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_uc1_in", "el_ucard1", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_u1_in", "el_use1", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_u1d_in", "el_use1_desc", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_uc2_in", "el_ucard2", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_u2_in", "el_use2", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_u2d_in", "el_use2_desc", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_uc3_in", "el_ucard3", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_u3_in", "el_use3", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_u3d_in", "el_use3_desc", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_uc4_in", "el_ucard4", "slideIn", 600, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_u4_in", "el_use4", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_u4d_in", "el_use4_desc", "fadeIn", 500, "in", {"easing":"easeOut"}),
    makeAnim("a_uf_in", "el_use_formats", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ait_in", "el_ai_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_ait_out", "el_ai_title", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_ais_in", "el_ai_sub", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ais_out", "el_ai_sub", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_aicard_in", "el_ai_card", "slideIn", 700, "in", {"easing":"cubicBezier:0.16,1,0.3,1"}),
    makeAnim("a_aid_in", "el_ai_desc", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_aicmd_in", "el_ai_cmd", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_aifl_in", "el_ai_flow", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_aiins_in", "el_ai_install", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctat_in", "el_cta_title", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_ctacard_in", "el_cta_card", "zoomIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctacmd_in", "el_cta_cmd", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctainst_in", "el_cta_install", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctainfo_in", "el_cta_info", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctaex_in", "el_cta_examples", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctastar_in", "el_cta_star", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_ctastar_loop", "el_cta_star", "pulse", 2500, "loop", {"easing":"easeInOut"}),
    makeAnim("a_l1_loop", "el_line1", "pulse", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("a_l1_out", "el_line1", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("a_l2_loop", "el_line2", "pulse", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("a_l3_loop", "el_line3", "pulse", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("a_lu_loop", "el_line_use", "pulse", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("a_l4_loop", "el_line4", "pulse", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("a_l5_loop", "el_line5", "pulse", 3000, "loop", {"easing":"easeInOut"}),
  ];

  const keyframeTracks = [
    makeKfTrack("kf_deco1", "el_deco_circle1", "position", [
      makeKf("kf_d1a", 0, {"x":1400,"y":-200}, "easeInOut"),
      makeKf("kf_d1b", 21000, {"x":1350,"y":-150}, "easeInOut"),
      makeKf("kf_d1c", 42000, {"x":1400,"y":-200}, "easeInOut"),
    ]),
    makeKfTrack("kf_deco2", "el_deco_circle2", "position", [
      makeKf("kf_d2a", 0, {"x":-200,"y":600}, "easeInOut"),
      makeKf("kf_d2b", 21000, {"x":-150,"y":550}, "easeInOut"),
      makeKf("kf_d2c", 42000, {"x":-200,"y":600}, "easeInOut"),
    ]),
    makeKfTrack("kf_l1_draw", "el_line1", "scale", [
      makeKf("kf_l1a", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_l1b", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
    makeKfTrack("kf_l2_draw", "el_line2", "scale", [
      makeKf("kf_l2a", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_l2b", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
    makeKfTrack("kf_l3_draw", "el_line3", "scale", [
      makeKf("kf_l3a", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_l3b", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
    makeKfTrack("kf_lu_draw", "el_line_use", "scale", [
      makeKf("kf_lua", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_lub", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
    makeKfTrack("kf_l4_draw", "el_line4", "scale", [
      makeKf("kf_l4a", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_l4b", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
    makeKfTrack("kf_l5_draw", "el_line5", "scale", [
      makeKf("kf_l5a", 0, {"scaleX":0,"scaleY":1}, "cubicBezier:0.16,1,0.3,1"),
      makeKf("kf_l5b", 600, {"scaleX":1,"scaleY":1}, "linear"),
    ]),
  ];

  const transitions = [
    makeTransition("tr_1_2", "track_titles", "el_hero_name", "el_pipe_title", "dissolve", 600, {"easing":"easeInOut"}),
    makeTransition("tr_2_3", "track_titles", "el_pipe_title", "el_feat_title", "dissolve", 600, {"easing":"easeInOut"}),
    makeTransition("tr_3_4", "track_titles", "el_feat_title", "el_use_title", "dissolve", 600, {"easing":"easeInOut"}),
    makeTransition("tr_4_5", "track_titles", "el_use_title", "el_ai_title", "dissolve", 600, {"easing":"easeInOut"}),
    makeTransition("tr_5_6", "track_titles", "el_ai_title", "el_cta_title", "dissolve", 600, {"easing":"easeInOut"}),
  ];

  const captions = [
    makeCaption("cap_01", "00:00:00.500", "00:00:05.000", "hypr-video-cli — programmatic video from your terminal", {"wordTimings":[{"word":"hypr-video-cli","start":0.5,"end":1.8},{"word":"—","start":1.8,"end":2},{"word":"programmatic","start":2,"end":2.7},{"word":"video","start":2.7,"end":3.1},{"word":"from","start":3.1,"end":3.4},{"word":"your","start":3.4,"end":3.7},{"word":"terminal","start":3.7,"end":4.3}]}),
    makeCaption("cap_02", "00:00:06.000", "00:00:11.500", "Three steps: describe, generate JSON, render MP4", {"wordTimings":[{"word":"Three","start":6,"end":6.4},{"word":"steps:","start":6.4,"end":6.8},{"word":"describe,","start":6.8,"end":7.4},{"word":"generate","start":7.4,"end":8},{"word":"JSON,","start":8,"end":8.5},{"word":"render","start":8.5,"end":9},{"word":"MP4","start":9,"end":9.5}]}),
    makeCaption("cap_03", "00:00:12.500", "00:00:18.500", "30+ animations, 20+ transitions, 50+ effects, keyframes and captions", {"wordTimings":[{"word":"30+","start":12.5,"end":12.9},{"word":"animations,","start":12.9,"end":13.5},{"word":"20+","start":13.5,"end":13.9},{"word":"transitions,","start":13.9,"end":14.5},{"word":"50+","start":14.5,"end":14.9},{"word":"effects,","start":14.9,"end":15.4},{"word":"keyframes","start":15.4,"end":16},{"word":"and","start":16,"end":16.2},{"word":"captions","start":16.2,"end":16.8}]}),
    makeCaption("cap_04", "00:00:19.500", "00:00:25.000", "Built for every format — YouTube, TikTok, Instagram and more", {"wordTimings":[{"word":"Built","start":19.5,"end":19.9},{"word":"for","start":19.9,"end":20.1},{"word":"every","start":20.1,"end":20.5},{"word":"format","start":20.5,"end":21},{"word":"—","start":21,"end":21.2},{"word":"YouTube,","start":21.2,"end":21.8},{"word":"TikTok,","start":21.8,"end":22.4},{"word":"Instagram","start":22.4,"end":23},{"word":"and","start":23,"end":23.2},{"word":"more","start":23.2,"end":23.6}]}),
    makeCaption("cap_05", "00:00:26.000", "00:00:32.000", "AI-powered — Claude builds and renders your video automatically", {"wordTimings":[{"word":"AI-powered","start":26,"end":26.8},{"word":"—","start":26.8,"end":27},{"word":"Claude","start":27,"end":27.5},{"word":"builds","start":27.5,"end":28},{"word":"and","start":28,"end":28.2},{"word":"renders","start":28.2,"end":28.7},{"word":"your","start":28.7,"end":29},{"word":"video","start":29,"end":29.4},{"word":"automatically","start":29.4,"end":30.2}]}),
    makeCaption("cap_06", "00:00:33.500", "00:00:40.000", "Start building today — open source, MIT license", {"wordTimings":[{"word":"Start","start":33.5,"end":33.9},{"word":"building","start":33.9,"end":34.5},{"word":"today","start":34.5,"end":35},{"word":"—","start":35,"end":35.2},{"word":"open","start":35.2,"end":35.6},{"word":"source,","start":35.6,"end":36.2},{"word":"MIT","start":36.2,"end":36.6},{"word":"license","start":36.6,"end":37.2}]}),
  ];

  return buildCanvas({
    bg: "linear-gradient(160deg, #e4eaf8, #dbe3f5 40%, #e8e0f8)",
    maxTime: 42000,
    elements,
    tracks,
    animations,
    keyframeTracks,
    transitions,
    captions,
    captionAnimation: {"preset":"karaoke","inType":"fadeIn","inDuration":300,"outType":"fadeOut","outDuration":200,"karaokeHighlightColor":"#4F6AFF","karaokeStyle":"classic","easing":"easeOut"},
    globalCaptionStyle: {"fontSize":30,"fontFamily":"Montserrat","fontColor":"#2d3550","fontWeight":600,"textAlign":"center","lineHeight":1.3,"charSpacing":1,"styles":[],"strokeWidth":0,"strokeColor":"#000000","shadowColor":"","shadowBlur":0,"shadowOffsetX":0,"shadowOffsetY":0,"backgroundColor":"","positionY":0.92,"originX":"center","originY":"center"},
    quality: "very_high",
  });
}
