export default function build(h) {
  const { buildCanvas, makeText, makeShape, makeEffect, makeTrack, makeAnim } = h;

  const elements = [
    makeShape("el_da1", "circle", "#6c63ff", {
      x: 1250,
      y: 150,
      w: 900,
      h: 900,
      start: 0,
      end: 4000,
      opacity: 0.18,
      name: "Deco A1",
    }),
    makeShape("el_da2", "circle", "#00d2ff", {
      x: 1250,
      y: 150,
      w: 900,
      h: 900,
      start: 4000,
      end: 8000,
      opacity: 0.18,
      name: "Deco A2",
    }),
    makeShape("el_da3", "circle", "#f72585", {
      x: 1250,
      y: 150,
      w: 900,
      h: 900,
      start: 8000,
      end: 12000,
      opacity: 0.18,
      name: "Deco A3",
    }),
    makeShape("el_da4", "circle", "#4cc9f0", {
      x: 1250,
      y: 150,
      w: 900,
      h: 900,
      start: 12000,
      end: 16000,
      opacity: 0.18,
      name: "Deco A4",
    }),
    makeShape("el_da5", "circle", "#6c63ff", {
      x: 1250,
      y: 150,
      w: 900,
      h: 900,
      start: 16000,
      end: 20000,
      opacity: 0.22,
      name: "Deco A5",
    }),
    makeShape("el_db1", "circle", "#a78bfa", {
      x: -180,
      y: -180,
      w: 600,
      h: 600,
      start: 0,
      end: 4000,
      opacity: 0.1,
      name: "Deco B1",
    }),
    makeShape("el_db2", "circle", "#38bdf8", {
      x: -180,
      y: -180,
      w: 600,
      h: 600,
      start: 4000,
      end: 8000,
      opacity: 0.1,
      name: "Deco B2",
    }),
    makeShape("el_db3", "circle", "#ff9ff3", {
      x: -180,
      y: -180,
      w: 600,
      h: 600,
      start: 8000,
      end: 12000,
      opacity: 0.1,
      name: "Deco B3",
    }),
    makeShape("el_db4", "circle", "#74b9ff", {
      x: -180,
      y: -180,
      w: 600,
      h: 600,
      start: 12000,
      end: 16000,
      opacity: 0.1,
      name: "Deco B4",
    }),
    makeShape("el_db5", "circle", "#a78bfa", {
      x: -180,
      y: -180,
      w: 600,
      h: 600,
      start: 16000,
      end: 20000,
      opacity: 0.12,
      name: "Deco B5",
    }),
    makeText("el_lbl1", "INTRODUCING", {
      x: 260,
      y: 378,
      w: 1400,
      h: 36,
      start: 300,
      end: 3800,
      name: "Label 1",
      size: 15,
      weight: 600,
      color: "#a78bfa",
      align: "center",
      charSpacing: 6,
    }),
    makeText("el_lbl2", "FEATURE 01  ·  AUTOMATION", {
      x: 260,
      y: 378,
      w: 1400,
      h: 36,
      start: 4300,
      end: 7800,
      name: "Label 2",
      size: 15,
      weight: 600,
      color: "#38bdf8",
      align: "center",
      charSpacing: 6,
    }),
    makeText("el_lbl3", "FEATURE 02  ·  ANALYTICS", {
      x: 260,
      y: 378,
      w: 1400,
      h: 36,
      start: 8300,
      end: 11800,
      name: "Label 3",
      size: 15,
      weight: 600,
      color: "#f72585",
      align: "center",
      charSpacing: 6,
    }),
    makeText("el_lbl4", "FEATURE 03  ·  COLLABORATION", {
      x: 260,
      y: 378,
      w: 1400,
      h: 36,
      start: 12300,
      end: 15800,
      name: "Label 4",
      size: 15,
      weight: 600,
      color: "#4cc9f0",
      align: "center",
      charSpacing: 6,
    }),
    makeText("el_lbl5", "START TODAY", {
      x: 260,
      y: 378,
      w: 1400,
      h: 36,
      start: 16300,
      end: 19800,
      name: "Label 5",
      size: 15,
      weight: 600,
      color: "#a78bfa",
      align: "center",
      charSpacing: 6,
    }),
    makeText("el_ttl1", "Synapse", {
      x: 260,
      y: 420,
      w: 1400,
      h: 160,
      start: 700,
      end: 3800,
      name: "Title 1",
      font: "Georgia",
      size: 128,
      weight: 700,
      color: "#ffffff",
      align: "center",
      useGradient: true,
      gradientColors: ["#a78bfa","#6c63ff","#38bdf8"],
    }),
    makeText("el_ttl2", "Work Smarter", {
      x: 260,
      y: 430,
      w: 1400,
      h: 140,
      start: 4700,
      end: 7800,
      name: "Title 2",
      font: "Georgia",
      size: 96,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_ttl3", "Real-time Insights", {
      x: 260,
      y: 430,
      w: 1400,
      h: 140,
      start: 8700,
      end: 11800,
      name: "Title 3",
      font: "Georgia",
      size: 96,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_ttl4", "One Team. One Platform.", {
      x: 260,
      y: 430,
      w: 1400,
      h: 140,
      start: 12700,
      end: 15800,
      name: "Title 4",
      font: "Georgia",
      size: 82,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_ttl5", "Free for 14 Days", {
      x: 260,
      y: 410,
      w: 1400,
      h: 160,
      start: 16700,
      end: 19800,
      name: "Title 5",
      font: "Georgia",
      size: 108,
      weight: 700,
      color: "#ffffff",
      align: "center",
      useGradient: true,
      gradientColors: ["#a78bfa","#6c63ff"],
    }),
    makeText("el_sub1", "The all-in-one platform for modern teams", {
      x: 410,
      y: 595,
      w: 1100,
      h: 60,
      start: 1200,
      end: 3800,
      name: "Sub 1",
      size: 28,
      color: "#94a3b8",
      align: "center",
    }),
    makeText("el_sub2", "Let AI handle repetitive tasks. Free your team to focus on what truly matters.", {
      x: 410,
      y: 590,
      w: 1100,
      h: 80,
      start: 5200,
      end: 7800,
      name: "Sub 2",
      size: 26,
      color: "#94a3b8",
      align: "center",
      lineHeight: 1.5,
    }),
    makeText("el_sub3", "Beautiful dashboards, instant reports, and data-driven decisions in real time.", {
      x: 410,
      y: 590,
      w: 1100,
      h: 80,
      start: 9200,
      end: 11800,
      name: "Sub 3",
      size: 26,
      color: "#94a3b8",
      align: "center",
      lineHeight: 1.5,
    }),
    makeText("el_sub4", "Connect your team across projects, time zones, and every tool you already use.", {
      x: 410,
      y: 590,
      w: 1100,
      h: 80,
      start: 13200,
      end: 15800,
      name: "Sub 4",
      size: 26,
      color: "#94a3b8",
      align: "center",
      lineHeight: 1.5,
    }),
    makeText("el_sub5", "No credit card required  ·  Setup in 5 minutes  ·  Cancel anytime", {
      x: 410,
      y: 572,
      w: 1100,
      h: 50,
      start: 17200,
      end: 19800,
      name: "Sub 5",
      size: 22,
      color: "#64748b",
      align: "center",
    }),
    makeShape("el_ctabtn", "rect", "#6c63ff", {
      x: 760,
      y: 650,
      w: 400,
      h: 72,
      start: 17700,
      end: 19800,
      name: "CTA Button",
      rx: 36,
      ry: 36,
    }),
    makeText("el_ctatxt", "Start Free Today", {
      x: 760,
      y: 656,
      w: 400,
      h: 60,
      start: 17700,
      end: 19800,
      name: "CTA Text",
      size: 22,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeEffect("el_fx1", [{"effectType":"flash","effectParams":{"intensity":0.7,"speed":8,"decay":0.4},"enabled":true}], { start: 3700, end: 4300 }),
    makeEffect("el_fx2", [{"effectType":"flash","effectParams":{"intensity":0.7,"speed":8,"decay":0.4},"enabled":true}], { start: 7700, end: 8300 }),
    makeEffect("el_fx3", [{"effectType":"flash","effectParams":{"intensity":0.7,"speed":8,"decay":0.4},"enabled":true}], { start: 11700, end: 12300 }),
    makeEffect("el_fx4", [{"effectType":"flash","effectParams":{"intensity":0.7,"speed":8,"decay":0.4},"enabled":true}], { start: 15700, end: 16300 }),
  ];

  const tracks = [
    makeTrack("track_title", "Titles", "text", ["el_ttl1","el_ttl2","el_ttl3","el_ttl4","el_ttl5"]),
    makeTrack("track_label", "Labels", "text", ["el_lbl1","el_lbl2","el_lbl3","el_lbl4","el_lbl5"]),
    makeTrack("track_sub", "Subtitles", "text", ["el_sub1","el_sub2","el_sub3","el_sub4","el_sub5"]),
    makeTrack("track_cta_text", "CTA Text", "text", ["el_ctatxt"]),
    makeTrack("track_cta_btn", "CTA Button", "shape", ["el_ctabtn"]),
    makeTrack("track_deco_a", "Deco A", "shape", ["el_da1","el_da2","el_da3","el_da4","el_da5"]),
    makeTrack("track_deco_b", "Deco B", "shape", ["el_db1","el_db2","el_db3","el_db4","el_db5"]),
    makeTrack("track_fx", "Effects", "effect", ["el_fx1","el_fx2","el_fx3","el_fx4"]),
  ];

  const animations = [
    makeAnim("anim_da1_lp", "el_da1", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_da2_lp", "el_da2", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_da3_lp", "el_da3", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_da4_lp", "el_da4", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_da5_lp", "el_da5", "breathe", 3000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_db1_lp", "el_db1", "breathe", 4000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_db2_lp", "el_db2", "breathe", 4000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_db3_lp", "el_db3", "breathe", 4000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_db4_lp", "el_db4", "breathe", 4000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_db5_lp", "el_db5", "breathe", 4000, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_lbl1_in", "el_lbl1", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_lbl1_ot", "el_lbl1", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_lbl2_in", "el_lbl2", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_lbl2_ot", "el_lbl2", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_lbl3_in", "el_lbl3", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_lbl3_ot", "el_lbl3", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_lbl4_in", "el_lbl4", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_lbl4_ot", "el_lbl4", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_lbl5_in", "el_lbl5", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_lbl5_ot", "el_lbl5", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_ttl1_in", "el_ttl1", "zoomIn", 900, "in", {"easing":"easeOut"}),
    makeAnim("anim_ttl1_ot", "el_ttl1", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_ttl2_in", "el_ttl2", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_ttl2_ot", "el_ttl2", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_ttl3_in", "el_ttl3", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_ttl3_ot", "el_ttl3", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_ttl4_in", "el_ttl4", "slideIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("anim_ttl4_ot", "el_ttl4", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_ttl5_in", "el_ttl5", "zoomIn", 900, "in", {"easing":"easeOut"}),
    makeAnim("anim_ttl5_ot", "el_ttl5", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("anim_sub1_in", "el_sub1", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_sub1_ot", "el_sub1", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_sub2_in", "el_sub2", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_sub2_ot", "el_sub2", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_sub3_in", "el_sub3", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_sub3_ot", "el_sub3", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_sub4_in", "el_sub4", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_sub4_ot", "el_sub4", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_sub5_in", "el_sub5", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("anim_sub5_ot", "el_sub5", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_ctabtn_in", "el_ctabtn", "zoomIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_ctabtn_ot", "el_ctabtn", "fadeOut", 400, "out", {"easing":"easeIn"}),
    makeAnim("anim_ctabtn_lp", "el_ctabtn", "pulse", 1500, "loop", {"easing":"easeInOut"}),
    makeAnim("anim_ctatxt_in", "el_ctatxt", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("anim_ctatxt_ot", "el_ctatxt", "fadeOut", 400, "out", {"easing":"easeIn"}),
  ];

  return buildCanvas({
    bg: "linear-gradient(135deg, #080818 0%, #0d0a1f 100%)",
    maxTime: 20000,
    elements,
    tracks,
    animations,
    quality: "high",
  });
}
