export default function build(h) {
  const { buildCanvas, makeText, makeShape, makeTrack, makeAnim } = h;

  const elements = [
    makeShape("el_bg_accent", "circle", "#3b82f6", {
      x: 0,
      y: 0,
      w: 1920,
      h: 1080,
      start: 0,
      end: 20000,
      opacity: 0.08,
      name: "BG Accent",
    }),
    makeText("el_s1_title", "Build Your First API", {
      x: 210,
      y: 300,
      w: 1500,
      h: 120,
      start: 300,
      end: 5500,
      name: "Tutorial Title",
      size: 84,
      weight: 700,
      color: "#ffffff",
      align: "center",
    }),
    makeText("el_s1_sub", "A step-by-step guide for beginners", {
      x: 360,
      y: 460,
      w: 1200,
      h: 50,
      start: 1200,
      end: 5500,
      name: "Tutorial Subtitle",
      size: 36,
      color: "#94a3b8",
      align: "center",
    }),
    makeText("el_s1_badge", "15 MIN READ  ·  BEGINNER", {
      x: 760,
      y: 560,
      w: 400,
      h: 35,
      start: 2000,
      end: 5500,
      opacity: 0.7,
      name: "Tutorial Badge",
      size: 20,
      weight: 600,
      color: "#3b82f6",
      align: "center",
    }),
    makeText("el_s2_num", "01", {
      x: 160,
      y: 180,
      w: 400,
      h: 300,
      start: 5500,
      end: 10000,
      opacity: 0.15,
      name: "Step 1 Number",
      size: 240,
      weight: 800,
      color: "#3b82f6",
    }),
    makeText("el_s2_title", "Set Up Your Environment", {
      x: 200,
      y: 400,
      w: 1200,
      h: 70,
      start: 5800,
      end: 10000,
      name: "Step 1 Title",
      size: 56,
      weight: 700,
      color: "#ffffff",
    }),
    makeText("el_s2_desc", "Install Node.js, create a new project folder,\nand initialize with npm init", {
      x: 200,
      y: 500,
      w: 1200,
      h: 80,
      start: 6300,
      end: 10000,
      name: "Step 1 Desc",
      size: 28,
      color: "#94a3b8",
    }),
    makeText("el_s3_num", "02", {
      x: 160,
      y: 180,
      w: 400,
      h: 300,
      start: 10000,
      end: 14500,
      opacity: 0.15,
      name: "Step 2 Number",
      size: 240,
      weight: 800,
      color: "#3b82f6",
    }),
    makeText("el_s3_title", "Define Your Routes", {
      x: 200,
      y: 400,
      w: 1200,
      h: 70,
      start: 10300,
      end: 14500,
      name: "Step 2 Title",
      size: 56,
      weight: 700,
      color: "#ffffff",
    }),
    makeText("el_s3_desc", "Create GET, POST, PUT, and DELETE endpoints\nusing Express.js routing", {
      x: 200,
      y: 500,
      w: 1200,
      h: 80,
      start: 10800,
      end: 14500,
      name: "Step 2 Desc",
      size: 28,
      color: "#94a3b8",
    }),
    makeText("el_s4_num", "03", {
      x: 160,
      y: 180,
      w: 400,
      h: 300,
      start: 14500,
      end: 20000,
      opacity: 0.15,
      name: "Step 3 Number",
      size: 240,
      weight: 800,
      color: "#3b82f6",
    }),
    makeText("el_s4_title", "Deploy & Test", {
      x: 200,
      y: 400,
      w: 1200,
      h: 70,
      start: 14800,
      end: 20000,
      name: "Step 3 Title",
      size: 56,
      weight: 700,
      color: "#ffffff",
    }),
    makeText("el_s4_desc", "Push to GitHub, deploy to Vercel,\nand test with Postman or curl", {
      x: 200,
      y: 500,
      w: 1200,
      h: 80,
      start: 15300,
      end: 20000,
      name: "Step 3 Desc",
      size: 28,
      color: "#94a3b8",
    }),
    makeText("el_s4_cta", "Full tutorial at devblog.com/api-guide", {
      x: 200,
      y: 660,
      w: 600,
      h: 35,
      start: 16500,
      end: 20000,
      name: "CTA",
      size: 24,
      color: "#3b82f6",
    }),
  ];

  const tracks = [
    makeTrack("track_bg", "Background", "shape", ["el_bg_accent"]),
    makeTrack("track_text", "Text", "text", ["el_s1_title","el_s1_sub","el_s1_badge","el_s2_num","el_s2_title","el_s2_desc","el_s3_num","el_s3_title","el_s3_desc","el_s4_num","el_s4_title","el_s4_desc","el_s4_cta"]),
  ];

  const animations = [
    makeAnim("a_01", "el_s1_title", "fadeIn", 1000, "in", {"easing":"easeOut"}),
    makeAnim("a_02", "el_s1_title", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_03", "el_s1_sub", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_04", "el_s1_sub", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_05", "el_s1_badge", "fadeIn", 600, "in", {"easing":"easeOut"}),
    makeAnim("a_06", "el_s1_badge", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_10", "el_s2_num", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_11", "el_s2_num", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_12", "el_s2_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_13", "el_s2_title", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_14", "el_s2_desc", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("a_15", "el_s2_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_20", "el_s3_num", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_21", "el_s3_num", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_22", "el_s3_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_23", "el_s3_title", "fadeOut", 600, "out", {"easing":"easeIn"}),
    makeAnim("a_24", "el_s3_desc", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("a_25", "el_s3_desc", "fadeOut", 500, "out", {"easing":"easeIn"}),
    makeAnim("a_30", "el_s4_num", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_31", "el_s4_title", "fadeIn", 800, "in", {"easing":"easeOut"}),
    makeAnim("a_32", "el_s4_desc", "fadeIn", 700, "in", {"easing":"easeOut"}),
    makeAnim("a_33", "el_s4_cta", "fadeIn", 600, "in", {"easing":"easeOut"}),
  ];

  return buildCanvas({
    bg: "#0f172a",
    maxTime: 20000,
    elements,
    tracks,
    animations,
    quality: "high",
  });
}
